"""Convert Scholl (1993) assembly-line instances to extended CSV files.

The script reads every ``.IN2`` file stored in a local ``Scholl93`` directory
and exports one CSV file per instance. The original task processing times and
precedence relations are retained, while the additional attributes required by
the multi-worker assembly-line model are generated synthetically.

Each output CSV contains the following columns:

``task_id``
    One-based task identifier from the original Scholl instance.
``execution_time``
    Original deterministic task processing time.
``ergonomic_value``
    Synthetic ergonomic load correlated with processing time and perturbed by
    random variation and occasional ergonomic shocks.
``area``
    Synthetic categorical work area (``external`` or ``internal``), assigned
    mainly according to the topological order of the precedence graph.
``predecessors``
    Direct predecessors represented as a stringified Python list.
``previous_station``
    Placeholder set to zero for every task. A valid previous allocation must
    subsequently be generated by solving the balancing problem.

Expected directory layout::

    script_directory/
    |-- scholl93_to_csv.py
    `-- Scholl93/
        |-- instance_1.IN2
        `-- ...

The generated files are written to ``script_directory/generated_csv``. Random
generation is reproducible for a fixed seed and a fixed order of input files.
"""

from collections import deque
import os
import re

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Input, output, and random-generation settings
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INSTANCES_DIR = os.path.join(SCRIPT_DIR, "Scholl93")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "generated_csv")

# A single generator is shared across all instances. This makes a complete run
# reproducible when both the seed and the input-file iteration order are fixed.
SEED = 42
RNG = np.random.default_rng(SEED)

# Fraction of tasks initially assigned to the external area and fraction whose
# area label is subsequently flipped to avoid perfect topological separation.
P_EXTERNAL = 0.60
FLIP_PROB = 0.08

# Parameters of the synthetic ergonomic-load model:
#
#   ergonomic load = ALPHA * processing time
#                    + BETA * random component.
#
# The random component is proportional to the standard deviation of processing
# times in the current instance. With probability P_SHOCK it is amplified to
# introduce ergonomically demanding tasks that are not necessarily the longest.
ALPHA = 0.40
BETA = 1.00
P_SHOCK = 0.15


def parse_scholl_instance(instance_path):
    """Read a Scholl ``.IN2`` file.

    The parser expects the first integer to be the number of tasks, followed by
    one processing time per task and then pairs ``(predecessor, successor)``.
    The precedence section ends with the sentinel pair ``(-1, -1)``.

    Parameters
    ----------
    instance_path : str
        Path to the input ``.IN2`` file.

    Returns
    -------
    tuple
        ``(tasks, processing_times, predecessors, successors)``, where tasks is
        a list and the remaining objects are dictionaries indexed by task ID.
    """

    with open(instance_path, "r", encoding="utf-8", errors="ignore") as file:
        text = file.read()

    # Extracting integers makes the parser independent of spaces and line
    # breaks used in the original text representation.
    numbers = list(map(int, re.findall(r"-?\d+", text)))
    number_of_tasks = numbers[0]
    raw_times = numbers[1 : 1 + number_of_tasks]
    precedence_data = numbers[1 + number_of_tasks :]

    tasks = list(range(1, number_of_tasks + 1))
    processing_times = {
        task: float(raw_times[task - 1])
        for task in tasks
    }

    predecessors = {task: [] for task in tasks}
    successors = {task: [] for task in tasks}

    for predecessor, successor in zip(
        precedence_data[0::2], precedence_data[1::2]
    ):
        if predecessor == -1 and successor == -1:
            break

        predecessors[successor].append(predecessor)
        successors[predecessor].append(successor)

    return tasks, processing_times, predecessors, successors


def compute_topological_order(tasks, predecessors, successors):
    """Return a topological order of the task-precedence graph.

    Kahn's algorithm is used: tasks with no remaining predecessors are added to
    a queue, and their outgoing arcs are removed as they are processed.

    Parameters
    ----------
    tasks : list[int]
        Task identifiers.
    predecessors : dict[int, list[int]]
        Direct predecessors of each task.
    successors : dict[int, list[int]]
        Direct successors of each task.

    Returns
    -------
    list[int]
        A valid topological ordering for an acyclic precedence graph.
    """

    in_degree = {task: len(predecessors[task]) for task in tasks}
    ready_tasks = deque(task for task in tasks if in_degree[task] == 0)
    topological_order = []

    while ready_tasks:
        task = ready_tasks.popleft()
        topological_order.append(task)

        for successor in successors[task]:
            in_degree[successor] -= 1
            if in_degree[successor] == 0:
                ready_tasks.append(successor)

    return topological_order


def generate_areas(tasks, topological_order):
    """Generate clustered ``external`` and ``internal`` area labels.

    The first ``P_EXTERNAL`` fraction of the topological order is labelled as
    external and the remaining tasks as internal. A small randomly selected
    fraction is then flipped so that area membership is related to, but not
    completely determined by, the precedence structure.

    Returns
    -------
    dict[int, str]
        Generated area label for each task.
    """

    number_external = int(round(P_EXTERNAL * len(tasks)))
    areas = {task: "internal" for task in tasks}

    for task in topological_order[:number_external]:
        areas[task] = "external"

    number_to_flip = int(round(FLIP_PROB * len(tasks)))
    if number_to_flip > 0:
        tasks_to_flip = RNG.choice(tasks, size=number_to_flip, replace=False)

        for task in tasks_to_flip:
            areas[task] = (
                "internal" if areas[task] == "external" else "external"
            )

    return areas


def generate_ergonomic_values(tasks, processing_times):
    """Generate a synthetic ergonomic load for every task.

    Processing time provides the correlated component of the load. Random
    instance-scaled variation prevents a deterministic time-load relationship,
    while occasional shocks create additional high-load observations.

    Returns
    -------
    dict[int, float]
        Generated ergonomic load indexed by task ID.
    """

    times = np.array(list(processing_times.values()))
    time_scale = np.std(times)
    ergonomic_values = {}

    for task in tasks:
        time_component = ALPHA * processing_times[task]
        random_component = RNG.uniform(0.5, 1.5) * time_scale

        if RNG.random() < P_SHOCK:
            random_component *= RNG.uniform(1.5, 2.5)

        ergonomic_values[task] = float(
            time_component + BETA * random_component
        )

    return ergonomic_values


def convert_instance(instance_path, output_path):
    """Convert one Scholl instance and save the extended data as CSV."""

    tasks, processing_times, predecessors, successors = parse_scholl_instance(
        instance_path
    )
    topological_order = compute_topological_order(
        tasks, predecessors, successors
    )
    areas = generate_areas(tasks, topological_order)
    ergonomic_values = generate_ergonomic_values(tasks, processing_times)

    instance_data = pd.DataFrame(
        {
            "task_id": tasks,
            "execution_time": [processing_times[task] for task in tasks],
            "ergonomic_value": [ergonomic_values[task] for task in tasks],
            "area": [areas[task] for task in tasks],
            "predecessors": [str(predecessors[task]) for task in tasks],
            # This column is deliberately only a placeholder. The balancing
            # model must be solved to obtain a meaningful initial allocation.
            "previous_station": [0 for _ in tasks],
        }
    )
    instance_data.to_csv(output_path, index=False)


def main():
    """Convert all ``.IN2`` files found in ``INSTANCES_DIR``."""

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    for filename in os.listdir(INSTANCES_DIR):
        if not filename.endswith(".IN2"):
            continue

        print(f"Processing {filename}...")

        instance_path = os.path.join(INSTANCES_DIR, filename)
        output_filename = filename.replace(".IN2", ".csv")
        output_path = os.path.join(OUTPUT_DIR, output_filename)

        convert_instance(instance_path, output_path)
        print(f"  -> Saved {output_path}")

    print("\nAll instances processed.")


if __name__ == "__main__":
    main()
